version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_DATABASE=apisolidpg
      - POSTGRESQL_USERNAME=postgresql
      - POSTGRESQL_PASSWORD=postgresql
